# Generated by Django 5.1.2 on 2024-10-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('building_type', models.CharField(choices=[('school', 'École'), ('admin', 'Administration'), ('bank', 'Banque'), ('theater', 'Théâtre')], max_length=20)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='building_photos/')),
            ],
        ),
    ]
